import type { Metadata } from "next";
import { TaskProvider } from "@/app/src/context/TaskContext";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pl">
      <body>
        <TaskProvider>
          <main className="min-h-screen bg-gray-50 text-gray-900">
            {children}
          </main>
        </TaskProvider>
      </body>
    </html>
  );
}
